# Export rom name
export VENDOR := dud

# DUD version info
DUD_VERSION_MAJOR := 3
DUD_VERSION_MINOR := 5.9.6
DUD_VERSION_MAINTENANCE :=
DUD_TYPE := darkobas
DUD_VERSION_TAG := BETA

# PA version info
PA_VERSION_MAJOR := 5
PA_VERSION_MINOR := 0
PA_VERSION_MAINTENANCE :=
PA_VERSION_TAG := ALPHA
