ifneq ($(DUD_TYPE),)
        ROM_NAME := $(PA_VERSION_MAJOR).$(PA_VERSION_MINOR)-$(DUD_TYPE)
        DUD_VERSION := $(DUD_TYPE)$(DUD_VERSION_MAJOR).$(DUD_VERSION_MINOR)$(DUD_VERSION_MAINTENANCE)
else
        DUD_VERSION := $(DUD_VERSION_MAJOR).$(DUD_VERSION_MINOR)$(DUD_VERSION_MAINTENANCE)
endif

export BUILD_DATE := $(shell date -u +%Y%m%d)
ifeq ($(TARGET_BUILD_VARIANT),user)
        export ODEX_BUILD := true
endif
export DUD_BUILD_NAME := $(DUD_VERSION)-$(BUILD_DATE)

PRODUCT_PROPERTY_OVERRIDES += \
    ro.dud.version=$(DUD_VERSION) \
    ro.dud.modversion=$(DUD_BUILD_NAME)



ifneq ($ROM_VERSION_TAG,"")
        VERSION := $(PA_VERSION_MAJOR).$(PA_VERSION_MINOR)$(PA_VERSION_MAINTENANCE)-$(PA_VERSION_TAG)
else
        VERSION := $(PA_VERSION_MAJOR).$(PA_VERSION_MINOR)$(PA_VERSION_MAINTENANCE)
endif

export ROM_VERSION := $(VERSION)-$(shell date -u +%Y%m%d)

PRODUCT_PROPERTY_OVERRIDES += \
    ro.pa.modversion=$(ROM_VERSION) \
    ro.pa.version=$(VERSION)

